global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8001']
  - job_name: 'workers'
    static_configs:
      - targets: ['workers:5555'] 