"""Add owner relationship to Channel model

Revision ID: 4ba62378f057
Revises: 5c40e4b1a89d
Create Date: 2025-07-23 16:06:24.639456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba62378f057'
down_revision: Union[str, None] = '5c40e4b1a89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'channels', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'owner_id')
    # ### end Alembic commands ###
