"""add_symbol_timestamp_fields_to_signal

Revision ID: 5c40e4b1a89d
Revises: e3b7db52b534
Create Date: 2025-07-08 18:33:28.230418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c40e4b1a89d'
down_revision: Union[str, None] = 'e3b7db52b534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_signals',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('signal_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_signals_id'), 'telegram_signals', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_signals_status'), 'telegram_signals', ['status'], unique=False)
    op.create_index(op.f('ix_telegram_signals_symbol'), 'telegram_signals', ['symbol'], unique=False)
    op.drop_index('ix_channels_url', table_name='channels')
    op.create_unique_constraint(None, 'channels', ['url'])
    op.drop_index('ix_payments_internal_transaction_id', table_name='payments')
    op.drop_index('ix_payments_stripe_payment_intent_id', table_name='payments')
    op.create_unique_constraint(None, 'payments', ['stripe_payment_intent_id'])
    op.create_unique_constraint(None, 'payments', ['internal_transaction_id'])
    op.add_column('signals', sa.Column('symbol', sa.String(length=20), nullable=False))
    op.add_column('signals', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.drop_index('ix_subscriptions_stripe_subscription_id', table_name='subscriptions')
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.drop_index('ix_users_stripe_customer_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_stripe_customer_id', 'users', ['stripe_customer_id'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_index('ix_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_column('signals', 'timestamp')
    op.drop_column('signals', 'symbol')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index('ix_payments_stripe_payment_intent_id', 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_index('ix_payments_internal_transaction_id', 'payments', ['internal_transaction_id'], unique=False)
    op.drop_constraint(None, 'channels', type_='unique')
    op.create_index('ix_channels_url', 'channels', ['url'], unique=False)
    op.drop_index(op.f('ix_telegram_signals_symbol'), table_name='telegram_signals')
    op.drop_index(op.f('ix_telegram_signals_status'), table_name='telegram_signals')
    op.drop_index(op.f('ix_telegram_signals_id'), table_name='telegram_signals')
    op.drop_table('telegram_signals')
    # ### end Alembic commands ###
